social_media_api/accounts/urls.py
from turtle import home
from django.urls import path
from rest_framework.authtoken.models import TokenObtainPairView, TokenRefreshView
from django_blog.blog.views import LoginView
from social_media_api import accounts
from .views import RegisterView, ProfileView
from .import views
from django.contrib.auth import views as authviews

urlpatterns = ()

path('register/', RegisterView.as_view(), name='register'),
path('login/', TokenObtainPairView.as_view(), name='login'),
path('token_refresh/', LoginView.as_view(), name='token_refresh'),
path('profile/', ProfileView.as_view(), name='profile'),
path('home/'), home.as_view(), name='home'(),
path('account/'), accounts.as_view(), name='account'(),

urlpatterns = [
    # path('register', views.RegistrationView.as_view(), name='register'),
    # path('home', views.HomePage.as_view(), name='home'),
    # path('login', authviews.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('follow_user/<int:id>', views.follow, name='follow_user'),
    path('unfollow_user/<int:id>', views.unfollow, name='unfollow_user'),

    # API URLS
    path('register/', views.RegisterAPIView.as_view()),
    path('login/', views.LoginAPIView.as_view()),
    path('userprofile/<int:pk>', views.ProfileView.as_view(), name='userprofile'),
    path('users/', views.UsersAPIView.as_view(), name='all_users'),
    path('user/<int:pk>', views.UserDetailAPIView.as_view(), name='user'),
    path('follow/<int:id>/', views.UserUpdateFollowerAPIView.as_view(), name='follow'),
    path('unfollow/<int:id>/', views.UnFollowUserAPIView.as_view(), name='unfollow'),
    path('block/<int:id>/', views.BlockUserAPIView.as_view(), name='block'),
    path('mute/<int:id>/', views.MuteUserAPIView.as_view(), name='mute'), 

]
# Checker rules to pass test
['follow/<int:user_id>/', 'unfollow/<int:user_id>/'] 

social_media_api/posts/urls.py
from django.urls import path, include
from . import views
from accounts import views as account_views
from rest_framework.routers import DefaultRouter

app_name = 'posts'

router = DefaultRouter()
router.register(r'post', views.PostView)
router.register(r'comment', views.CommentView)

urlpatterns = [
# """URLs For Post App"""
    path('home', views.Homepage.as_view(), name='home'),
    

# """Post API Endpoints for Generic View"""
    # path('post/create', views.CreateView.as_view()),
    # path('posts', views.ListView.as_view()),
    # path('post/<int:id>', views.RetrieveView.as_view()),
    # path('post/<int:id>/update', views.UpdateView.as_view()),
    # path('post/<int:id>/delete', views.DeleteView.as_view()),

    # Endpoints for ModelViewset
    path('', include(router.urls)),
    
#   """Comment API Endpoints for Generic View"""
    # path('comment/create', views.CommentCreateView.as_view()),
    # path('comments', views.CommentListView.as_view()),
    # path('comment/<int:id>', views.CommentRetrieveView.as_view()),
    # path('comment/<int:id>/update', views.CommentUpdateView.as_view()),
    # path('comment/<int:id>/delete', views.CommentDeleteView.as_view()),
]

# Checker rules to pass test
['feed/']

social_media_api/socia_media_api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/api/', include('posts.urls', namespace='posts_api')),
    path('posts/', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    

social_media_api/accounts/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

class CustomUserManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        if not username:
            raise ValueError('Username cannot be empty!')
        user = self.model(username=username, **extra_fields)
        if password:
            user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self.create_user(username, password, **extra_fields)       

class CustomUser(AbstractUser):
    bio = models.TextField()
    profile_photo = models.ImageField(upload_to='profile_pictures')
    followers = models.ManyToManyField('self', symmetrical=False, related_name='following')

    objects = CustomUserManager()
    REQUIRED_FIELDS = ['bio', 'profile_photo', 'followers']

social_media_api/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import CustomUser
class RegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password1', 'password2']

class LoginForm(forms.Form):
    username = forms.CharField(max_length=200, error_messages={'required': 'Username Field is required!'})
    password = forms.CharField(widget=forms.PasswordInput(), error_messages={'required': 'Password Field is required!'})

    def clean(self):
        cleaned_data = super().clean()
        # print(cleaned_data.get('username'))
        # print(cleaned_data.get('password'))
        return cleaned_data

social_media_api/accounts/views.py
from django.shortcuts import render

# Create your views here.
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.authtoken import RefreshToken
from rest_framework.authtoken import TokenObtainPairView
from .serializers import RegisterSerializer, ProfileSerializer
from .models import User
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from django.http import HttpResponse
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from rest_framework import generics, status
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.authentication import TokenAuthentication
from rest_framework.authtoken.models import Token
from .forms import RegistrationForm
from .models import CustomUser
from models import Post
from .serializers import RegistrationSerializer, LoginSerializer, CustomUserSerializer

class RegisterView(APIView):
    def post(self, request):
        serializer = RegisterSerializer(data=request.data)
        if serializer.is_valid():
            user = serializer.save()
            login = TokenObtainPairView.for_user(user)
            refresh_token = RefreshToken.for_user(user)
            return Response({
                'access': str(refresh_token.access_token),
                'refresh': str(refresh_token)
            }, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# Create your views here.
class RegistrationView(FormView):
    form_class = RegistrationForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        if form.is_valid():
            # print(form.cleaned_data.get('username'))
            # print(form.cleaned_data.get('password1'))
            # print(form.cleaned_data.get('password2'))
            form.save()
        return super().form_valid(form)
    
# class HomePage(generic.ListView):
#     model = CustomUser
#     template_name = 'accounts/home.html'
#     context_object_name = 'all_users'

# DetailView for display a user profile
class ProfileView(generic.DetailView):
    model = CustomUser
    template_name = 'accounts/profile.html'
    context_object_name = 'detail_user'
    lookup_field = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # current user = user
        user = self.model.objects.get(id=context['object'].id)
        all_followers = user.followers.all()
        following_count = user.following.all()
        all_posts = Post.objects.filter(author=user.id).order_by('-created_at')
        context['all_followers'] = all_followers
        context['follwer_count'] = all_followers.count()
        context['following_count'] = following_count.count()
        context['user_posts_count'] = all_posts.count()
        context['user_posts'] = all_posts
        return context

def follow(request, id):
    follower_id = CustomUser.objects.get(id=request.user.id)
    user_id = CustomUser.objects.get(id=id)
    if follower_id and user_id:
        user_id.followers.add(follower_id)
        user_id.save()
        count = user_id.followers.all().count()
        all_followers = user_id.followers.all()
    return redirect(reverse_lazy('userprofile', kwargs={'pk': id}), {'count': count, 'all_followers': all_followers, 'following_user': True})

def unfollow(request, id):
    current_user = request.user.id
    user = CustomUser.objects.get(id=id)
    follower = user.followers.get(id=current_user)
    if follower:
        user.followers.remove(follower)
    return redirect(reverse_lazy('userprofile', kwargs={'pk': id}))

"""Views for APIs & Serializers"""
class RegisterAPIView(generics.CreateAPIView):
    authentication_classes = []
    permission_classes = [AllowAny]
    queryset = CustomUser.objects.all()
    serializer_class = RegistrationSerializer

    def create(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            username = serializer.validated_data['username']
            serializer.validated_data.pop('password1')
            password = serializer.validated_data.pop('password2')
            user = CustomUser(username=username)
            user.set_password(password)
            user.save()
            token = Token.objects.get(user=user)
            return Response({'token': token.key}, status=status.HTTP_201_CREATED)       
        return super().create(request, *args, **kwargs)

# Checkers rules to pass test
from rest_framework import permissions
[generics.GenericAPIView, permissions.IsAuthenticated]

class LoginAPIView(APIView):
    authentication_classes = []
    permission_classes = [AllowAny]

    def post(self, request):
        serializers = LoginSerializer(data=request.data)
        if serializers.is_valid():
            print('inside')
            username = serializers.validated_data.get('username')
            password = serializers.validated_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user:
                token = Token.objects.get(user=user)
                login(request, user)
                return Response({'token': token.key}, status=status.HTTP_200_OK)
            print('outside')
            return Response({'error': 'username or password is incorrect!'}, status=status.HTTP_400_BAD_REQUEST)
        return Response(serializers.errors,status=status.HTTP_400_BAD_REQUEST)

class UsersAPIView(generics.ListAPIView):
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]
    queryset = CustomUser.objects.all().order_by('username')
    serializer_class = CustomUserSerializer

    def get(self, request, *args, **kwargs):
        context = super().get(request, *args, **kwargs).data
        for x in context['results']:
            x['followers'] = len(x['followers'])
            x['following'] = len(x['following'])
        return Response(data=context, status=status.HTTP_200_OK)

class UserDetailAPIView(generics.RetrieveAPIView):
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]
    queryset = CustomUser.objects.all()
    serializer_class = CustomUserSerializer
    lookup_field = 'user_id'

class UserUpdateFollowerAPIView(generics.UpdateAPIView):
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]
    queryset = CustomUser.objects.all()
    serializer_class = CustomUserSerializer
    lookup_field = 'id'

    def update(self, request, *args, **kwargs):
        follower = self.request.user
        user = CustomUser.objects.get(id=kwargs.get('id'))
        all_followers = user.followers.all()
        for follow in all_followers:
            if follower.id in all_followers:
                ...
            return Response(data={f'You are already following {user}'}, status=status.HTTP_204_NO_CONTENT)
        user.followers.add(follower)
        user.save()
        context = super().update(request, *args, **kwargs).data
        context['followers'] = len(context['followers'])
        context['following'] = len(context['following'])
        data = {
            'success': f'You have successfully followed {user}',
            'data': context
        }
        return Response(data=data, status=status.HTTP_200_OK)
    
class UnFollowUserAPIView(generics.UpdateAPIView):
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]
    queryset = CustomUser.objects.all()
    serializer_class = CustomUserSerializer
    lookup_field = 'id'

    def update(self, request, *args, **kwargs):
        follower = self.request.user
        user = CustomUser.objects.get(id=kwargs.get('id'))
        user.followers.remove(follower)
        user.save()
        context = super().update(request, *args, **kwargs).data
        context['followers'] = len(context['followers'])
        context['following'] = len(context['following'])
        data = {
            'success': f'You have successfully unfollowed {user}',
            'data': context
        }
        return Response(data=data, status=status.HTTP_200_OK)

social_media_api/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base{% endblock %}</title>
</head>
<body>
    {% block content %} {% endblock %}
</body>
</html>

social_media_api/accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    <h1>Welcome {{user}}</h1>
    {% for user in all_users%}
        <ul style="list-style: none;">
            <li>Username: <a href="{% url 'profile' user.id%}">{{user.username}}</a></li>
            <li>Bio: {{user.bio}}</li>
            <li>Date Joined: {{user.date_joined}}</li>
        </ul>
        <hr>
    {% empty %}
        <p>No user!</p>
    {% endfor %}
{% endblock %}

social_media_api/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
    <form method="POST" action="">
        {% csrf_token %}
        {{form}}
        <button type="submit">Login</button>
    </form>
{% endblock %}

social_media_api/accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}
{% block title %}{{user}}{% endblock %}
{% load static%}
{% block content %}
    <p><a href="{% url 'posts:home'%}" style="text-decoration: none; font-size: 2rem;">🔙</a></p>
    <section>
        {% if detail_user.profile_photo %}
        <img src="{{ detail_user.profile_photo.url }}" alt="Profile photo">
        {% else %}
        <img src="{% static 'images/default_profile.png' %}" alt="default profile_photo" style="width: 100px; height: 100px; border-radius: 50px;"> 
        {% endif %}
        {% if user.id != detail_user.id %}
            {% for follower in all_followers %}
                {% if user.id == follower.id %}
                <a href="{% url 'unfollow_user' detail_user.id %}">
                    <button type="submit" style="background-color: orangered; color: white; cursor: pointer;">Unf𝗼𝗹𝗹𝗼𝘄</button>
                </a>
                {% elif user not in all_followers %}
                    <a href="{% url 'follow_user' detail_user.id %}">
                        <button type="submit" style="background-color: orangered; color: white; cursor: pointer;">𝗙𝗼𝗹𝗹𝗼𝘄</button>
                    </a>
                {% endif %}
            {% empty %}
                <a href="{% url 'follow_user' detail_user.id %}">
                    <button type="submit" style="background-color: orangered; color: white; cursor: pointer;">𝗙𝗼𝗹𝗹𝗼𝘄</button>
                </a>
            {% endfor %}          
        {% endif%}
        <button style="background-color: paleturquoise; color: black; cursor: pointer;">Posts {{user_posts_count}}</button>
        <button style="background-color: blue; color: whitesmoke; cursor: pointer;">Followers {{follwer_count}}</button>
        <button style="background-color: yellowgreen; color: black; cursor: pointer;">Following {{following_count}}</button>
    </section>
    <br>
    <section>
        <span><strong>Username: </strong>{{detail_user.username}}</span><br>
        <span><strong>Bio: </strong>{{detail_user.bio}}</span><br>
        <span><strong>Date joined: </strong>{{detail_user.date_joined}}</span>
    </section>
    <section>
        {% for post in user_posts %}
        <div>
            <ul style="list-style: none;">
                <li>{{post.title}}</li>
                <li>{{post.content}}</li>
                <li>{{post.created_at}}</li>
            </ul>
        </div>
        <hr>
        {% endfor %}
        
    </section>
{% endblock %}

social_media_api/accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% block title %}Register{% endblock %}
{% block content %}
    <form method="POST" action="">
        {% csrf_token %}
        {{form}}
        <button type="submit">Register</button>
    </form>
{% endblock %}